//自动生成的文件，请勿修改
export namespace R{
  export let image = {
    setting1: "setting/setting1",
    setting10: "setting/setting10",
    setting2: "setting/setting2",
    setting3: "setting/setting3",
    setting4: "setting/setting4",
    setting5: "setting/setting5",
    setting6: "setting/setting6",
    setting7: "setting/setting7",
    setting8: "setting/setting8",
    setting9: "setting/setting9",
    loading_background: "framework/loading/loading_background",
    loading_ico: "framework/loading/loading_ico",
    toast_background: "framework/toast/toast_background",
    goblins_pma_goblin_girl: "goblin-girl/goblins-pma",
    goblins_pma_goblins: "goblins/goblins-pma",
    btnAdd: "images/common/btnAdd",
    btnBack: "images/common/btnBack",
    btnHome: "images/common/btnHome",
    btnMore: "images/common/btnMore",
    btnSetting: "images/common/btnSetting",
    btnSignin1: "images/common/btnSignin1",
    btnSignin2: "images/common/btnSignin2",
    btnSignin3: "images/common/btnSignin3",
    btnSignin4: "images/common/btnSignin4",
    btnSkip: "images/common/btnSkip",
    btn_close: "images/common/btn_close",
    btn_rect_bg_1: "images/common/btn_rect_bg_1",
    btn_rect_bg_2: "images/common/btn_rect_bg_2",
    guide_finger: "images/common/guide_finger",
    ico_body: "images/common/ico_body",
    ico_btn_dial: "images/common/ico_btn_dial",
    ico_carpet: "images/common/ico_carpet",
    ico_curtain: "images/common/ico_curtain",
    ico_face_fail: "images/common/ico_face_fail",
    ico_face_success: "images/common/ico_face_success",
    ico_fail: "images/common/ico_fail",
    ico_floor: "images/common/ico_floor",
    ico_hair: "images/common/ico_hair",
    ico_heart: "images/common/ico_heart",
    ico_home: "images/common/ico_home",
    ico_lamp: "images/common/ico_lamp",
    ico_restart: "images/common/ico_restart",
    ico_share: "images/common/ico_share",
    ico_skin: "images/common/ico_skin",
    ico_sofa: "images/common/ico_sofa",
    ico_step: "images/common/ico_step",
    ico_table: "images/common/ico_table",
    ico_video: "images/common/ico_video",
    ico_wall: "images/common/ico_wall",
    level_state_check: "images/common/level_state_check",
    level_state_disable: "images/common/level_state_disable",
    level_state_normal: "images/common/level_state_normal",
    line: "images/common/line",
    play1: "images/common/play1",
    play2: "images/common/play2",
    play3: "images/common/play3",
    play4: "images/common/play4",
    setting_music: "images/common/setting_music",
    setting_off: "images/common/setting_off",
    setting_on: "images/common/setting_on",
    setting_sound: "images/common/setting_sound",
    signin_coin_1: "images/common/signin_coin_1",
    signin_coin_2: "images/common/signin_coin_2",
    signin_coin_3: "images/common/signin_coin_3",
    signin_coin_4: "images/common/signin_coin_4",
    signin_coin_5: "images/common/signin_coin_5",
    ui_back_forwad: "images/common/ui_back_forwad",
    ui_base_board_blue: "images/common/ui_base_board_blue",
    ui_base_board_top: "images/common/ui_base_board_top",
    ui_bottom_panel1: "images/common/ui_bottom_panel1",
    ui_bottom_panel2: "images/common/ui_bottom_panel2",
    ui_btn_blue: "images/common/ui_btn_blue",
    ui_btn_green: "images/common/ui_btn_green",
    ui_btn_green_2_0: "images/common/ui_btn_green_2_0",
    ui_btn_green_2_1: "images/common/ui_btn_green_2_1",
    ui_btn_green_2_2: "images/common/ui_btn_green_2_2",
    ui_btn_green_2_3: "images/common/ui_btn_green_2_3",
    ui_chapter_icon: "images/common/ui_chapter_icon",
    ui_cloth_bg: "images/common/ui_cloth_bg",
    ui_cloth_icon: "images/common/ui_cloth_icon",
    ui_coin_bar: "images/common/ui_coin_bar",
    ui_curent_level_dot: "images/common/ui_curent_level_dot",
    ui_curent_level_dot_bg: "images/common/ui_curent_level_dot_bg",
    ui_daily_gift_icon: "images/common/ui_daily_gift_icon",
    ui_discount_tag: "images/common/ui_discount_tag",
    ui_focus: "images/common/ui_focus",
    ui_gift_box_body: "images/common/ui_gift_box_body",
    ui_gift_box_upper: "images/common/ui_gift_box_upper",
    ui_gift_frame: "images/common/ui_gift_frame",
    ui_gift_progress: "images/common/ui_gift_progress",
    ui_guide_hand: "images/common/ui_guide_hand",
    ui_hot_tag: "images/common/ui_hot_tag",
    ui_icon_claimed: "images/common/ui_icon_claimed",
    ui_icon_coin: "images/common/ui_icon_coin",
    ui_icon_correct: "images/common/ui_icon_correct",
    ui_icon_hint_0: "images/common/ui_icon_hint_0",
    ui_icon_hint_1: "images/common/ui_icon_hint_1",
    ui_icon_hint_2: "images/common/ui_icon_hint_2",
    ui_icon_hint_3: "images/common/ui_icon_hint_3",
    ui_icon_next: "images/common/ui_icon_next",
    ui_icon_pause: "images/common/ui_icon_pause",
    ui_icon_resume: "images/common/ui_icon_resume",
    ui_item_normal: "images/common/ui_item_normal",
    ui_item_selected: "images/common/ui_item_selected",
    ui_level_complete_title: "images/common/ui_level_complete_title",
    ui_light_small: "images/common/ui_light_small",
    ui_none: "images/common/ui_none",
    ui_notify_title: "images/common/ui_notify_title",
    ui_popup_panel: "images/common/ui_popup_panel",
    ui_price_baseboard: "images/common/ui_price_baseboard",
    ui_reward_bg: "images/common/ui_reward_bg",
    ui_reward_current_bg: "images/common/ui_reward_current_bg",
    ui_reward_gray_bg: "images/common/ui_reward_gray_bg",
    ui_room_icon: "images/common/ui_room_icon",
    ui_selected: "images/common/ui_selected",
    ui_toggle: "images/common/ui_toggle",
    ui_toggle_baseboard: "images/common/ui_toggle_baseboard",
    icon_carpet1: "images/decor/icon_carpet1",
    icon_carpet2: "images/decor/icon_carpet2",
    icon_carpet3: "images/decor/icon_carpet3",
    icon_carpet4: "images/decor/icon_carpet4",
    icon_carpet5: "images/decor/icon_carpet5",
    icon_curtain1: "images/decor/icon_curtain1",
    icon_curtain2: "images/decor/icon_curtain2",
    icon_curtain3: "images/decor/icon_curtain3",
    icon_curtain4: "images/decor/icon_curtain4",
    icon_curtain5: "images/decor/icon_curtain5",
    icon_floor1: "images/decor/icon_floor1",
    icon_floor2: "images/decor/icon_floor2",
    icon_floor3: "images/decor/icon_floor3",
    icon_floor4: "images/decor/icon_floor4",
    icon_floor5: "images/decor/icon_floor5",
    icon_lamp1: "images/decor/icon_lamp1",
    icon_lamp2: "images/decor/icon_lamp2",
    icon_lamp3: "images/decor/icon_lamp3",
    icon_lamp4: "images/decor/icon_lamp4",
    icon_lamp5: "images/decor/icon_lamp5",
    icon_sofa1: "images/decor/icon_sofa1",
    icon_sofa2: "images/decor/icon_sofa2",
    icon_sofa3: "images/decor/icon_sofa3",
    icon_sofa4: "images/decor/icon_sofa4",
    icon_sofa5: "images/decor/icon_sofa5",
    icon_table1: "images/decor/icon_table1",
    icon_table2: "images/decor/icon_table2",
    icon_table3: "images/decor/icon_table3",
    icon_table4: "images/decor/icon_table4",
    icon_table5: "images/decor/icon_table5",
    icon_wall1: "images/decor/icon_wall1",
    icon_wall2: "images/decor/icon_wall2",
    icon_wall3: "images/decor/icon_wall3",
    icon_wall4: "images/decor/icon_wall4",
    icon_cloth_0: "images/skins/icon_cloth_0",
    icon_cloth_1: "images/skins/icon_cloth_1",
    icon_cloth_2: "images/skins/icon_cloth_2",
    icon_cloth_3: "images/skins/icon_cloth_3",
    icon_cloth_4: "images/skins/icon_cloth_4",
    icon_cloth_5: "images/skins/icon_cloth_5",
    icon_hair_0: "images/skins/icon_hair_0",
    icon_hair_1: "images/skins/icon_hair_1",
    icon_hair_2: "images/skins/icon_hair_2",
    icon_hair_3: "images/skins/icon_hair_3",
    icon_hair_4: "images/skins/icon_hair_4",
    icon_hair_5: "images/skins/icon_hair_5",
    btnProbability: "images/view/btnProbability",
    ui_award_item_board: "images/view/ui_award_item_board",
    ui_background_light_blue: "images/view/ui_background_light_blue",
    ui_baseboard_gray: "images/view/ui_baseboard_gray",
    ui_baseboard_luck: "images/view/ui_baseboard_luck",
    ui_box: "images/view/ui_box",
    ui_ico_coin_big: "images/view/ui_ico_coin_big",
    ui_ico_heart_big: "images/view/ui_ico_heart_big",
    ui_ico_tooltip_big: "images/view/ui_ico_tooltip_big",
    ui_item_card_xn: "images/view/ui_item_card_xn",
    ui_luck_item_checked: "images/view/ui_luck_item_checked",
    ui_progress_bar: "images/view/ui_progress_bar",
    ui_progress_bg: "images/view/ui_progress_bg",
    ui_title_baseboard: "images/view/ui_title_baseboard",
    enligsh_chinese: "loadingBar/enligsh-chinese",
    font: "loadingBar/font",
    mikado_outline_shadow: "loadingBar/mikado_outline_shadow",
    alien: "loadSpine/alien",
    singleColor: "singleColor",
    spineboy: "spineboy/spineboy",
    gold: "texture/gold",
  }
  export let prefab = {
    RoomItem: "prefabs/items/RoomItem",
    Loading: "framework/loading/Loading",
    Toast: "framework/toast/Toast",
    gold: "prefabs/gold",
    FailureView: "view/FailureView",
    PauseView: "view/PauseView",
    SuccessfulView: "view/SuccessfulView",
  }
  export let fire = {
    LobbyScene: "scene/LobbyScene",
  }
  export let wav = {
    cheering: "audio/cheering",
  }
  export let sound = {
    ding: "audio/ding",
    music_logo: "audio/music_logo",
  }
  export let ttf = {
    Alibaba_PuHuiTi_Regular: "font/Alibaba-PuHuiTi-Regular",
  }
  export let atlas = {
    goblins_goblin_girl: "goblin-girl/goblins",
    goblins_goblins: "goblins/goblins",
    alien_ess: "loadSpine/alien-ess",
  }
  export let json = {
    goblins_goblin_girl: "goblin-girl/goblins",
    goblins_goblins: "goblins/goblins",
    alien_ess: "loadSpine/alien-ess",
    spineboy: "spineboy/spineboy",
  }
  export let txt = {
    spineboy: "spineboy/spineboy",
  }
  //场景开始
  export let scene = {
    FightingScene: "FightingScene",
    LobbyScene: "LobbyScene",
    LoadingScene: "LoadingScene",
    MenuScene: "MenuScene",
    LoaderTestScene1: "LoaderTestScene1",
    LoaderTestScene2: "LoaderTestScene2",
    PrefabAssetTest: "PrefabAssetTest",
    ToastTest: "ToastTest",
  }
  //场景结束

  //Bundle 开始
  export let bundle = {
    core: "core",
    lobby: "lobby",
    resources: "resources",
  }
  //Bundle 结束
}
